export const HAZARD_LASER_TELEGRAPH_MS = 1100;
export const HAZARD_LASER_ACTIVE_MS = 380;
export const HAZARD_LASER_FADE_MS = 320;
export const HAZARD_LASER_WIDTH = 32;
export const HAZARD_LASER_DAMAGE = 1;

export const HAZARD_MISSILE_TELEGRAPH_MS = 1000;
export const HAZARD_MISSILE_ACTIVE_MS = 320;
export const HAZARD_MISSILE_FADE_MS = 400;
export const HAZARD_MISSILE_BLAST_RADIUS = 80;

export const HAZARD_SHOCKWAVE_TELEGRAPH_MS = 900;
export const HAZARD_SHOCKWAVE_ACTIVE_MS = 1200;
export const HAZARD_SHOCKWAVE_FADE_MS = 300;
export const HAZARD_SHOCKWAVE_BAND = 36;
export const HAZARD_SHOCKWAVE_MAX_RADIUS = 360;

export const HAZARD_SPAWN_MIN_INTERVAL_MS = 12000;
export const HAZARD_SPAWN_MAX_INTERVAL_MS = 20000;
export const HAZARD_FIRST_SPAWN_DELAY_MS = 16000;
