export const HAZARD_LASER_TELEGRAPH_MS = 1100;
export const HAZARD_LASER_ACTIVE_MS = 380;
export const HAZARD_LASER_FADE_MS = 320;
export const HAZARD_LASER_WIDTH = 32;
export const HAZARD_LASER_DAMAGE = 1;

export const HAZARD_SPAWN_MIN_INTERVAL_MS = 14000;
export const HAZARD_SPAWN_MAX_INTERVAL_MS = 22000;
export const HAZARD_FIRST_SPAWN_DELAY_MS = 18000;
